import PropTypes from "prop-types";

const Celebrating = ({ className = "" }) => {
  return (
    <section
      className={`
        w-full 
        max-w-[1440px] 
        mx-auto 
        bg-whitesmoke 
        overflow-hidden 
        flex 
        flex-col 
        items-start 
        justify-start 
        py-16 
        md:py-28 
        px-4 
        md:px-16 
        box-border 
        text-left 
        text-29xl 
        text-border-primary 
        font-text 
        mq450:gap-5 
        mq750:gap-10 
        mq750:py-[47px] 
        mq750:px-8 
        mq750:box-border 
        mq1050:pt-[73px] 
        mq1050:pb-[73px] 
        mq1050:box-border 
        ${className}
      `}
    >
      <div 
        className="
          self-stretch 
          flex 
          flex-col 
          md:flex-row 
          items-center 
          justify-start 
          flex-wrap 
          content-center 
          gap-12 
          md:gap-20 
          mq450:gap-5 
          mq750:gap-10
        "
      >
        <div 
          className="
            flex-1 
            flex 
            flex-col 
            items-start 
            justify-start 
            gap-8 
            min-w-[400px] 
            mq750:gap-4 
            mq750:min-w-full 
            w-full
          "
        >
          <div className="self-stretch flex flex-col items-start justify-start gap-6">
            <h1 
              className="
                m-0 
                self-stretch 
                relative 
                text-inherit 
                font-bold 
                font-[inherit] 
                text-3xl 
                md:text-4xl 
                lg:text-5xl 
                mq450:text-10xl 
                mq1050:text-19xl
              "
            >
              Celebrating Our Success: Major Government Contracts Completed with Excellence
            </h1>
            <h3 
              className="
                m-0 
                self-stretch 
                relative 
                text-xl 
                md:text-5xl 
                font-medium 
                font-[inherit] 
                mq450:text-lgi
              "
            >
              Our commitment to quality and efficiency has led us to successfully complete numerous government contracts. Each project showcases our expertise and dedication to meeting the needs of our clients.
            </h3>
          </div>
          <div className="self-stretch flex flex-col items-start justify-start font-text-small-normal">
            <div 
              className="
                self-stretch 
                flex 
                flex-col 
                md:flex-row 
                items-start 
                justify-start 
                py-2 
                px-0 
                gap-6 
                mq750:flex-wrap
              "
            >
              <div 
                className="
                  flex-1 
                  flex 
                  flex-col 
                  items-start 
                  justify-start 
                  gap-2 
                  min-w-[192px]
                "
              >
                <b 
                  className="
                    self-stretch 
                    relative 
                    leading-[120%] 
                    text-3xl 
                    md:text-4xl 
                    lg:text-5xl 
                    mq450:text-10xl 
                    mq450:leading-[35px] 
                    mq1050:text-19xl 
                    mq1050:leading-[46px]
                  "
                >
                  100%
                </b>
                <h3 
                  className="
                    m-0 
                    self-stretch 
                    relative 
                    text-xl 
                    md:text-5xl 
                    font-medium 
                    font-text 
                    mq450:text-lgi
                  "
                >
                  Delivering results that exceed expectations every time.
                </h3>
              </div>
              <div 
                className="
                  flex-1 
                  flex 
                  flex-col 
                  items-start 
                  justify-start 
                  gap-2 
                  min-w-[192px]
                "
              >
                <b 
                  className="
                    self-stretch 
                    relative 
                    leading-[120%] 
                    text-3xl 
                    md:text-4xl 
                    lg:text-5xl 
                    mq450:text-10xl 
                    mq450:leading-[35px] 
                    mq1050:text-19xl 
                    mq1050:leading-[46px]
                  "
                >
                  100%
                </b>
                <h3 
                  className="
                    m-0 
                    self-stretch 
                    relative 
                    text-xl 
                    md:text-5xl 
                    font-medium 
                    font-text 
                    mq450:text-lgi
                  "
                >
                  Transforming visions into reality through strategic execution.
                </h3>
              </div>
            </div>
          </div>
        </div>
        <img
          className="
            flex-1 
            relative 
            max-w-full 
            overflow-hidden 
            max-h-full 
            object-cover 
            min-w-[400px] 
            mq750:min-w-full 
            w-full 
            md:w-auto
          "
          loading="lazy"
          alt=""
          src="/ibel3.jpg"
        />
      </div>
    </section>
  );
};

Celebrating.propTypes = {
  className: PropTypes.string,
};

export default Celebrating;
